# Generated by Django 4.0.9 on 2023-04-14 14:33

from django.conf import settings
import django.core.management.utils
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=256, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('secret_key', models.CharField(default=django.core.management.utils.get_random_secret_key, max_length=255)),
                ('is_block', models.BooleanField(default=False)),
                ('max_feeds', models.IntegerField(default=10)),
                ('max_dashboards', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_public', models.URLField(default=False, max_length=256)),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedValue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('name_color', models.CharField(default='', max_length=256)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vat_backend.dashboard')),
                ('feeds', models.ManyToManyField(null=True, to='vat_backend.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('value_color', models.CharField(blank=True, max_length=256)),
                ('background_color', models.CharField(blank=True, max_length=256)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('image_data', models.TextField(blank=True)),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('signature', models.CharField(max_length=256)),
                ('color_value', models.CharField(max_length=256)),
                ('curve_type', models.CharField(max_length=256)),
                ('grid_color', models.CharField(max_length=256)),
                ('background', models.CharField(max_length=256)),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('on_color', models.CharField(max_length=256)),
                ('off_color', models.CharField(max_length=256)),
                ('number_auto_on', models.IntegerField()),
                ('number_auto_off', models.IntegerField()),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('widget_color', models.CharField(max_length=256)),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('number_of_element', models.IntegerField()),
                ('signature', models.CharField(max_length=256)),
                ('color', models.CharField(blank=True, max_length=256)),
                ('text_color', models.CharField(max_length=256)),
                ('arc_width', models.FloatField()),
                ('animate', models.BooleanField()),
                ('max_value', models.FloatField()),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            bases=('vat_backend.widget',),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vat_backend.widget')),
                ('equation', models.CharField(max_length=256)),
                ('precision', models.IntegerField()),
                ('suffix', models.CharField(max_length=256)),
                ('background', models.CharField(max_length=256)),
                ('value_color', models.CharField(max_length=256)),
            ],
            bases=('vat_backend.widget',),
        ),
    ]
